-- MySQL Script generated by MySQL Workbench
-- Tue Sep  6 15:16:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema site
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema site
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `site` DEFAULT CHARACTER SET utf8 ;
USE `site` ;

-- -----------------------------------------------------
-- Table `site`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(70) NULL,
  `contenu` LONGTEXT NULL,
  `court` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site`.`articles_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`articles_categories` (
  `id` INT NOT NULL,
  `nom` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site`.`articles_catégories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`articles_catégories` (
  `articles_id` INT NOT NULL,
  `catégories_id` INT NOT NULL,
  PRIMARY KEY (`articles_id`, `catégories_id`),
  CONSTRAINT `fk_articles_has_catégories_articles`
    FOREIGN KEY (`articles_id`)
    REFERENCES `site`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_catégories_catégories1`
    FOREIGN KEY (`catégories_id`)
    REFERENCES `site`.`articles_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_has_catégories_catégories1_idx` ON `site`.`articles_catégories` (`catégories_id` ASC) VISIBLE;

CREATE INDEX `fk_articles_has_catégories_articles_idx` ON `site`.`articles_catégories` (`articles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `site`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mot` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site`.`articles_has_articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`articles_has_articles` (
  `articles_id` INT NOT NULL,
  `articles_id1` INT NOT NULL,
  PRIMARY KEY (`articles_id`, `articles_id1`),
  CONSTRAINT `fk_articles_has_articles_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `site`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_articles_articles2`
    FOREIGN KEY (`articles_id1`)
    REFERENCES `site`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_has_articles_articles2_idx` ON `site`.`articles_has_articles` (`articles_id1` ASC) VISIBLE;

CREATE INDEX `fk_articles_has_articles_articles1_idx` ON `site`.`articles_has_articles` (`articles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `site`.`articles_has_articles_catégories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`articles_has_articles_catégories` (
  `articles_id` INT NOT NULL,
  `articles_catégories_articles_id` INT NOT NULL,
  `articles_catégories_catégories_id` INT NOT NULL,
  PRIMARY KEY (`articles_id`, `articles_catégories_articles_id`, `articles_catégories_catégories_id`),
  CONSTRAINT `fk_articles_has_articles_catégories_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `site`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_articles_catégories_articles_catégories1`
    FOREIGN KEY (`articles_catégories_articles_id` , `articles_catégories_catégories_id`)
    REFERENCES `site`.`articles_catégories` (`articles_id` , `catégories_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_has_articles_catégories_articles_catégories1_idx` ON `site`.`articles_has_articles_catégories` (`articles_catégories_articles_id` ASC, `articles_catégories_catégories_id` ASC) VISIBLE;

CREATE INDEX `fk_articles_has_articles_catégories_articles1_idx` ON `site`.`articles_has_articles_catégories` (`articles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `site`.`articles_has_articles1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`articles_has_articles1` (
  `articles_id` INT NOT NULL,
  `articles_id1` INT NOT NULL,
  PRIMARY KEY (`articles_id`, `articles_id1`),
  CONSTRAINT `fk_articles_has_articles1_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `site`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_articles1_articles2`
    FOREIGN KEY (`articles_id1`)
    REFERENCES `site`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_has_articles1_articles2_idx` ON `site`.`articles_has_articles1` (`articles_id1` ASC) VISIBLE;

CREATE INDEX `fk_articles_has_articles1_articles1_idx` ON `site`.`articles_has_articles1` (`articles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `site`.`articles_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`articles_tags` (
  `articles_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`articles_id`, `tags_id`),
  CONSTRAINT `fk_articles_has_tags_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `site`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `site`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_articles_has_tags_tags1_idx` ON `site`.`articles_tags` (`tags_id` ASC) VISIBLE;

CREATE INDEX `fk_articles_has_tags_articles1_idx` ON `site`.`articles_tags` (`articles_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `site`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`commentaires` (
  `id` INT NOT NULL,
  `pseudo` VARCHAR(70) NULL,
  `site` VARCHAR(255) NULL,
  `mail` VARCHAR(255) NULL,
  `contenu` LONGTEXT NULL,
  `articles_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `site`.`users` (
  `id` INT NOT NULL,
  `login` VARCHAR(70) NULL,
  `pass` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
